name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build with Buildozer
        id: buildozer
        run: |
            git clone https://github.com/kivy/buildozer.git
            cd buildozer
            sudo python3 setup.py install
            cd ..


            sudo apt-get update
            sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
            pip3 install --upgrade Cython==0.29.19 virtualenv
            export PATH=$PATH:~/.local/bin/
            yes | buildozer android debug
            yes | cp -f buildozer-64bit.spec buildozer.spec
            yes | buildozer android debug

      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: 'bin/*armeabi-v7a*.apk'
          path: 'bin/*arm64-v8a*.apk'


