name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build with Buildozer
        run: |
            git clone https://github.com/kivy/buildozer.git
            cd buildozer
            sudo python3 setup.py install
            cd ..


            sudo apt-get update
            sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
            pip3 install --upgrade Cython==0.29.19 virtualenv
            export PATH=$PATH:~/.local/bin/
            yes | buildozer android debug deploy

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
