name: Build
on: [push, pull_request]

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android32:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildozer action
        uses: ArtemSBulgakov/buildozer-action@v1.1.3
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}

    build-android64:
      name: Build for Android64
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Buildozer action
          uses: ArtemSBulgakov/buildozer-action@v1.1.3
          id: buildozer
          with:
            run: yes | cp -f buildozer-64bit.spec buildozer.spec
            command: buildozer android debug
            buildozer_version: stable

        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
            name: package
            path: ${{ steps.buildozer.outputs.filename }}